### ISSUE TITLE
torch.size problem. How can I solve it?

### ISSUE THREAD

**Issue by 9o0p** [weirdseed/vits-ncnn-convert-tool#11]
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([52, 192]) from checkpoint, the shape in current model is torch.Size([40, 192]).

**Comment by weirdseed** [comment]
Please check if the symbols in your config.json file match the model.

**Comment by 9o0p** [comment]
solved it. thanks
