### ISSUE TITLE
RuntimeError: Symbols can not be empty

### ISSUE THREAD

**Issue by RRRainick** [weirdseed/vits-ncnn-convert-tool#6]
RunTimeError when converting so-vits 4.0 model 

```shell
.\convert_model.exe -c path\config.json -m path\model.pth -fp16
Traceback (most recent call last):
  File "convert_model.py", line 221, in <module>
  File "convert_model.py", line 132, in main
RuntimeError: Symbols can not be empty!
[29556] Failed to execute script 'convert_model' due to unhandled exception!
```

not sure whether it is helpful, but here's my config.json

```json
{
  "train": {
    "log_interval": 200,
    "eval_interval": 800,
    "seed": 1234,
    "epochs": 10000,
    "learning_rate": 0.00015,
    "betas": [
      0.8,
      0.99
    ],
    "eps": 1e-09,
    "batch_size": 9,
    "fp16_run": false,
    "lr_decay": 0.999875,
    "segment_size": 10240,
    "init_lr_ratio": 1,
    "warmup_epochs": 0,
    "c_mel": 45,
    "c_kl": 1.0,
    "use_sr": true,
    "max_speclen": 512,
    "port": "8001",
    "keep_ckpts": 20
  },
  "data": {
    "training_files": "filelists/train.txt",
    "validation_files": "filelists/val.txt",
    "max_wav_value": 32768.0,
    "sampling_rate": 44100,
    "filter_length": 2048,
    "hop_length": 512,
    "win_length": 2048,
    "n_mel_channels": 80,
    "mel_fmin": 0.0,
    "mel_fmax": 22050
  },
  "model": {
    "inter_channels": 192,
    "hidden_channels": 192,
    "filter_channels": 768,
    "n_heads": 2,
    "n_layers": 6,
    "kernel_size": 3,
    "p_dropout": 0.1,
    "resblock": "1",
    "resblock_kernel_sizes": [
      3,
      7,
      11
    ],
    "resblock_dilation_sizes": [
      [
        1,
        3,
        5
      ],
      [
        1,
        3,
        5
      ],
      [
        1,
        3,
        5
      ]
    ],
    "upsample_rates": [
      8,
      8,
      2,
      2,
      2
    ],
    "upsample_initial_channel": 512,
    "upsample_kernel_sizes": [
      16,
      16,
      4,
      4,
      4
    ],
    "n_layers_q": 3,
    "use_spectral_norm": false,
    "gin_channels": 256,
    "ssl_dim": 256,
    "n_speakers": 200
  },
  "spk": {
    "megumi": 0
  }
}
```

**Comment by weirdseed** [comment]
> RunTimeError when converting so-vits 4.0 model
> 
> ```shell
> .\convert_model.exe -c path\config.json -m path\model.pth -fp16
> Traceback (most recent call last):
>   File "convert_model.py", line 221, in <module>
>   File "convert_model.py", line 132, in main
> RuntimeError: Symbols can not be empty!
> [29556] Failed to execute script 'convert_model' due to unhandled exception!
> ```
> 
> not sure whether it is helpful, but here's my config.json
> 
> ```json
> {
>   "train": {
>     "log_interval": 200,
>     "eval_interval": 800,
>     "seed": 1234,
>     "epochs": 10000,
>     "learning_rate": 0.00015,
>     "betas": [
>       0.8,
>       0.99
>     ],
>     "eps": 1e-09,
>     "batch_size": 9,
>     "fp16_run": false,
>     "lr_decay": 0.999875,
>     "segment_size": 10240,
>     "init_lr_ratio": 1,
>     "warmup_epochs": 0,
>     "c_mel": 45,
>     "c_kl": 1.0,
>     "use_sr": true,
>     "max_speclen": 512,
>     "port": "8001",
>     "keep_ckpts": 20
>   },
>   "data": {
>     "training_files": "filelists/train.txt",
>     "validation_files": "filelists/val.txt",
>     "max_wav_value": 32768.0,
>     "sampling_rate": 44100,
>     "filter_length": 2048,
>     "hop_length": 512,
>     "win_length": 2048,
>     "n_mel_channels": 80,
>     "mel_fmin": 0.0,
>     "mel_fmax": 22050
>   },
>   "model": {
>     "inter_channels": 192,
>     "hidden_channels": 192,
>     "filter_channels": 768,
>     "n_heads": 2,
>     "n_layers": 6,
>     "kernel_size": 3,
>     "p_dropout": 0.1,
>     "resblock": "1",
>     "resblock_kernel_sizes": [
>       3,
>       7,
>       11
>     ],
>     "resblock_dilation_sizes": [
>       [
>         1,
>         3,
>         5
>       ],
>       [
>         1,
>         3,
>         5
>       ],
>       [
>         1,
>         3,
>         5
>       ]
>     ],
>     "upsample_rates": [
>       8,
>       8,
>       2,
>       2,
>       2
>     ],
>     "upsample_initial_channel": 512,
>     "upsample_kernel_sizes": [
>       16,
>       16,
>       4,
>       4,
>       4
>     ],
>     "n_layers_q": 3,
>     "use_spectral_norm": false,
>     "gin_channels": 256,
>     "ssl_dim": 256,
>     "n_speakers": 200
>   },
>   "spk": {
>     "megumi": 0
>   }
> }
> ```

SO-VITS 4.0 models are not supported, and this project only supports the original [vits models](https://github.com/jaywalnut310/vits) or [moegoe models](https://github.com/CjangCjengh/MoeGoe)
